[env]
ISO_DIR = "target/__iso__"
ISO_OUT = "target/m5kos.iso"

[env.development]
KERNEL_BIN = "${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_NAME}"

[env.release]
KERNEL_BIN = "${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_NAME}"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.iso]
script = '''
mkdir -p ${ISO_DIR}/boot/grub
cp config/grub.cfg ${ISO_DIR}/boot/grub/
cp ${KERNEL_BIN} ${ISO_DIR}/boot/m5kos.bin
grub-mkrescue -o ${ISO_OUT} ${ISO_DIR}
rm -rf ${ISO_DIR}
'''
dependencies = ["build"]

[tasks.run]
command = "qemu-system-x86_64"
args = ["-cdrom", "${ISO_OUT}"]
dependencies = ["iso"]

[tasks.default]
alias = "iso"

[config]
skip_core_tasks = true